"use strict";
(function(){

	// 
	// ......
	// SOCKET.IO...
	// NoSQL structured/unstructured data...
	// JSON...
	// MOCK SERVICE: KEEN.IO/Custom RESTful API WITH NODE AND SOCKET.IO...
	//
	
	// What's the biggest challenge with our current setup game plan for sdk development?
	// How does this affect the companies we are selling to?...
	// 
	// Data tracking and analysis for all communication applications...

	//  

	//
	//
	// What was your game plan on development(iOS & Android)...?
	// 
	//

    // 
    // BIZ... 
    //
	// Where was the tech stack at when you guys first started...
	// What is your current cloud computing solution? Service? Custom?
	// 1. Structure(solidify(anti-pivot))...
	// 2. Validate Distribution & Monetization(execute it)...
	// 3. Innovation(we are doing what no other is doing in our industry...(it is a required technology...)(Who can hustle and hack the fastest?))...
	// 4. Raise debt, hoard equity...
	// 5. Do VC's apply to us(at all?)?...
	// 6. Tell a structured story...
	// 7. MVP sucks, make something badass(PEEK, high-performance iterations...)...
	// 8. 10x investment(unless it's a grant...)...
	// 9. What's the plan?...
	// 10. We are limited by our network...
	// (What did we do this week?)...

	//
	// TECH...
	// 

	// (Converstion rates for us a 100% until a better solution is provided or the client does not need the application or service anymore...)...

	// 
	// 1. Ideas must have a solid foundation, but must scale...
	// 2. Keep the big ideas in mind...
	// 3. (Trigger.IO and PhoneGap suck ass...)...(BaaS, IaaS, PaaS, Multi-tenancy...)...
	// 4. (Find the right custom solution for this data platform...)(Pill-Fill: Consultation...)...
	// 5. Complexity mitigation in the stack...(Hardware, frameworks, middleware, source-code...)...
	// 6. System arcs and devs are very different...(elegant full stack development...)...
	// 7. Android/iOS/Local JSON persistence/JSON document stores/Node.js/Crypto/NoSQL/...
	// 8. Java, Objective-C/Swift, JavaScript/Node.js/NoSQL...
	// 9. What are our dependencies...
	// 10. Agile/SCRUM/etc...
	// (Visual tools for SCRUM/Agile structure?)...
	// DOCUMENTATION/STRUCTURE...
	// Corey Crowley 864-346-8053...
	// (Make sure the tech stack is perfect for our needs K.I.S.S.)...
	// 

	// income, balance sheet, cash flow statement...

	const fs = require('fs'),
	// arguement vector...
	// [node, /Users/byrdannfox/jsHacker/file-system, watcher-argv.js]...
	filename = process.argv[2];
	if (!filename) {
		throw Error("It must be watching a file...");
	}
	fs.watch(filename, function () {
		console.log("File " + filename + " just changed!");
	});
	console.log("Now watching " + filename + " for changes...");



}());

